import argparse
import sys
from pathlib import Path
from typing import Tuple, Union

import imageio.v2 as iio
import numpy as np
from tqdm import tqdm

import pca as pca_utils

# Upper IR filter list
UPPER_IR = ['780IR', '850IR', '940IR', '1050IR']
# UV and IR filter list
UV_IR = ['UV', 'IR']

# False coloring combinations
false_colorings = {'A': [('B', 2), ('B', 3), ('B', 4)],
                   'B': [('A', 4), ('A', 5), ('A', 5)],
                   'C': [('C', 5), ('C', 4), ('C', 1)],
                   'D': [('E', 3), ('E', 5), ('E', 6)],
                   'E': [('A', 3), ('A', 4), ('A', 5)],
                   'F': [('B', 3), ('D', 3), ('E', 3)],
                   'G': [('A', 1), ('A', 3), ('A', 4)],
                   'H': [('B', 3), ('B', 2), ('B', 0)],
                   'I': [('C', 4), ('C', 2), ('C', 1)],
                   'J': [('E', 1), ('E', 2), ('E', 3)],
                   'K': [('E', 4), ('E', 2), ('E', 0)],
                   'L': [('A', 2), ('A', 2), ('A', 16)]}


def normalize(x, x_min, x_max, a=0., b=1.):
    """
    Transform x in the range [x_min, x_max] to the range [a, b]
    """
    return a + (x - x_min) * (b - a) / (x_max - x_min)


def main():
    # Parse args
    parser = argparse.ArgumentParser()
    parser.add_argument('--input-dir', '-i', metavar='PATH', type=str,
                        required=True,
                        help='Path to directory of spectral TIFs')
    parser.add_argument('--output-dir', '-o', metavar='PATH', type=str,
                        help='Output directory for generated images. If not '
                             'provided, the current working directory is used')
    parser.add_argument('--prefix', type=str, default='',
                        help='If provided, prepends the given prefix to all '
                             'files generated by this script')
    parser.add_argument('--pca-dir', metavar='PATH', type=str,
                        help='If provided, attempt to load precomputed PCA '
                             'sets from the given path')
    parser.add_argument('--normalize', action=argparse.BooleanOptionalAction,
                        default=True,
                        help='Normalize false color images to the [0, 1] range '
                             'using min-max scaling')
    parser.add_argument('--stretch', action=argparse.BooleanOptionalAction,
                        default=False,
                        help='Enable contrast stretching')
    parser.add_argument('--stretch-min', metavar='FLOAT', type=float, default=2,
                        help='Stretch minimum percentile')
    parser.add_argument('--stretch-max', metavar='FLOAT', type=float,
                        default=98, help='Stretch maximum percentile')
    args = parser.parse_args()

    # Set up input and output dirs
    in_dir = Path(args.input_dir)
    if args.output_dir is None:
        out_dir = Path()
    else:
        out_dir = Path(args.output_dir)

    # Get file list
    files = list(in_dir.glob('*.tif'))

    # Collect the file lists for each PCA combination
    pca_sets = {'A': files, 'B': list(), 'C': list(), 'D': list(), 'E': list(),
                'F': list()}
    for filename in files:
        # Set B
        if not any(spectrum in filename.name for spectrum in UPPER_IR):
            pca_sets['B'].append(filename)

        # Set C
        if any(spectrum in filename.name for spectrum in UV_IR):
            pca_sets['C'].append(filename)

        # Set D
        if any(spectrum in filename.name for spectrum in UV_IR) and not any(
                spectrum in filename.name for spectrum in UPPER_IR):
            pca_sets['D'].append(filename)

        # Set E
        if not any(spectrum in filename.name for spectrum in UV_IR):
            pca_sets['E'].append(filename)

        # Set F - IR780+
        if any(spectrum in filename.name for spectrum in UPPER_IR):
            pca_sets['F'].append(filename)

    # Generate PCA sets
    if args.pca_dir is not None:
        print(f'Loading precomputed PCA sets from {args.pca_dir}...')
        pca_files = load_pca_sets(Path(args.pca_dir), pca_sets.keys())
    else:
        pca_files = generate_pca_sets(out_dir, pca_sets, args.prefix)

    # Setup contrast stretching
    stretch = None
    if args.stretch:
        stretch = (args.stretch_min, args.stretch_max)

    # Generate false color images
    generate_false_coloring(out_dir,
                            pca_files,
                            args.prefix,
                            args.normalize,
                            stretch)


def load_pca_sets(pca_dir: Path, set_ids):
    """Load the file paths for pre-existing PCA sets on disk"""
    pca_files = {}
    for set_id in set_ids:
        set_dir = pca_dir / set_id
        if not set_dir.exists():
            print(f'Error: PCA set {set_id} not found in PCA directory '
                  f'{str(pca_dir)}')
            sys.exit(1)
        pca_files[set_id] = sorted(set_dir.glob('*.tif'))
    return pca_files


def generate_pca_sets(out_dir, pca_sets, prefix: str = ''):
    """Run PCA on the various PCA set configurations"""
    # Ignore warnings from imageio
    import warnings
    warnings.simplefilter("ignore")

    # Calculate PCA on the various PCA sets
    pca_files = {}
    for set_id, band_paths in tqdm(pca_sets.items(),
                                   desc='Generating PCA sets'):
        set_label = f'{prefix}PCA_{set_id}'

        # Set up the output directory
        pca_out = out_dir / 'PCA' / set_id
        pca_out.mkdir(parents=True, exist_ok=True)

        # Write the list of input files into the output dir
        with (pca_out / f'{set_label}_input_files.txt').open('w') as of:
            of.writelines([f'{f.name}\n' for f in sorted(band_paths)])

        # Load inputs
        images = np.stack([iio.imread(f) for f in band_paths])

        # Run PCA
        pca_utils.enable_print_progress(False)
        pca = pca_utils.pca_fit(images)
        pca_images = pca_utils.pca_apply_transform(images, pca)

        # Save the outputs
        padding = len(str(pca.n_components_))
        file_list = []
        for idx, img in enumerate(pca_images):
            output_path = pca_out / f'{set_label}_{idx:0{padding}}.tif'
            file_list.append(output_path)
            iio.imwrite(output_path, img.astype(np.float32))

        # Collect a sorted list of generated PCA files
        pca_files[set_id] = file_list

    return pca_files


def generate_false_coloring(out_dir, pca_files,
                            prefix: str = '',
                            scale: bool = False,
                            stretch: Union[Tuple[float, float], None] = None):
    """Generate all false color image combinations"""
    # Setup output directory
    fc_dir = out_dir / 'False Coloring'
    fc_dir.mkdir(parents=True, exist_ok=True)
    for fc_id, channels in tqdm(false_colorings.items(),
                                desc='Generating false color sets'):
        fc_label = f'{prefix}FC{fc_id}'

        # Collect the list of files for each channel
        suffix = ''
        channel_files = []
        for set_id, idx in channels:
            cn_file = pca_files[set_id][idx]
            suffix = f'{suffix}_{set_id}{idx}'
            channel_files.append(cn_file)

        # Load images into 3-channel images
        img = np.dstack([iio.imread(f) for f in channel_files])

        # (optional) Normalize intensity to [0, 1]
        if scale:
            x_min = np.amin(img)
            x_max = np.amax(img)
            img = normalize(img, x_min, x_max)

        # (optional) contrast stretch to percentile range
        if stretch is not None:
            suffix = f'_{stretch[0]:.2f}-{stretch[1]:.2f}{suffix}'
            x_min = np.percentile(img, stretch[0])
            x_max = np.percentile(img, stretch[1])
            img = np.clip(normalize(img, x_min, x_max), 0., 1.)

        # Write the list of input files into the output dir
        with (fc_dir / f'{fc_label}{suffix}_input_files.txt').open('w') as of:
            of.writelines([f'{f.name}\n' for f in channel_files])

        # Write output
        out_file = fc_dir / f'{fc_label}{suffix}.tif'
        iio.imwrite(out_file, img)


if __name__ == '__main__':
    main()
